name = "lead"
main = "src/index.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]
account_id = "30c9362191318777b71647145decda48"

workers_dev = true

[vars]
ALLOWED_EMAIL = "guillaumelauzier@gmail.com"
ACCESS_TEAM_DOMAIN = "axalnetwork.cloudflareaccess.com"
ACCESS_AUD = "f9cbce05165afb5af93e5929ff93dc4591aa18cd8234244327e78fd29fa849dd"
ACCESS_APP_AUD = "d9cde0e58496fb9f512cf697c93f587bcbf4e8faf363726ff83c1a8190fe0158"

[[d1_databases]]
binding = "DB"
database_name = "aidatasignal-leads"
database_id = "ecd7272e-533d-4e01-81ba-e1b98bce6e1c"

[[kv_namespaces]]
binding = "SESSIONS"
id = "302eb1a32ae64ce588dee452e14b3217"

[[queues.producers]]
binding = "LEAD_QUEUE"
queue = "aidatasignal-lead-jobs"

[[queues.consumers]]
queue = "aidatasignal-lead-jobs"
max_batch_size = 10
max_batch_timeout = 5

[[routes]]
pattern = "api.aidatasignal.com"
custom_domain = true

[[routes]]
pattern = "aidatasignal.com"
custom_domain = true

[[routes]]
pattern = "www.aidatasignal.com"
custom_domain = true

[[routes]]
pattern = "app.aidatasignal.com"
custom_domain = true
