source "https://rubygems.org"

gem 'jekyll', '~>4.3.2'

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-paginate-v2"
  gem 'jekyll-archives'
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?

gem "webrick"

gem "kramdown-parser-gfm", "~> 1.1"

gem "rouge"

gem 'eventmachine', '~> 1.2.7'
