-- Task #5: Seed the e_types registry with ~80 profile types. Uses
-- INSERT OR REPLACE keyed by `id` so re-running the migration refreshes
-- definitions without duplicating rows.

INSERT OR REPLACE INTO e_types (id, label, category, entity_kind, parent_type_id, detection_signals_json, enrichment_predicates_json, seed_sources_json, icon, color) VALUES
-- ===== Capital =====
('investor', 'Investor', 'capital', 'company', NULL,
 '{"url_patterns":["/portfolio","/team","/about","/fund"],"title_keywords":["venture","capital","fund","invest"],"content_keywords":["portfolio","AUM","check size","stage"],"evidence_required":["fund_aum OR portfolio_size"]}',
 '["aum","check_size_min","check_size_max","stages","sectors","portfolio_count","fund_number"]',
 '{"urls":["https://www.crunchbase.com/hub/venture-capital-firms"],"search_queries":["venture capital firm"]}',
 'briefcase','#7c3aed'),
('investor_vc', 'Venture Capital firm', 'capital', 'company', 'investor',
 '{"url_patterns":["/portfolio","/team"],"title_keywords":["venture capital","VC","fund"],"content_keywords":["series a","seed","portfolio company","limited partner"],"evidence_required":["fund_aum OR portfolio_count"]}',
 '["aum","check_size_min","check_size_max","stages","sectors","portfolio_count","lps"]',
 '{"urls":["https://www.crunchbase.com/hub/venture-capital-firms"],"search_queries":["venture capital firm site:crunchbase.com"]}',
 'briefcase','#7c3aed'),
('investor_pe', 'Private Equity firm', 'capital', 'company', 'investor',
 '{"url_patterns":["/portfolio","/funds"],"title_keywords":["private equity","buyout","PE"],"content_keywords":["buyout","mezzanine","LBO","control investment"],"evidence_required":["fund_aum"]}',
 '["aum","strategy","sectors","portfolio_count","fund_vintage"]',
 '{"urls":[],"search_queries":["private equity firm portfolio"]}',
 'briefcase','#5b21b6'),
('investor_angel', 'Angel Investor', 'capital', 'person', 'investor',
 '{"url_patterns":["/about","/bio"],"title_keywords":["angel investor","angel"],"content_keywords":["angel investments","portfolio","syndicate","first check"],"evidence_required":["angel_portfolio_count"]}',
 '["check_size_typical","stages","sectors","angel_portfolio_count","syndicate_membership"]',
 '{"urls":["https://angel.co"],"search_queries":["angel investor portfolio"]}',
 'star','#a78bfa'),
('investor_corporate_vc', 'Corporate VC', 'capital', 'company', 'investor',
 '{"url_patterns":["/ventures","/cvc"],"title_keywords":["ventures","corporate venture","strategic invest"],"content_keywords":["strategic investment","corporate parent","platform integration"],"evidence_required":["corporate_parent"]}',
 '["corporate_parent","aum","stages","sectors","strategic_thesis"]',
 '{"urls":[],"search_queries":["corporate venture capital arm"]}',
 'building','#6d28d9'),
('investor_micro_vc', 'Micro VC', 'capital', 'company', 'investor',
 '{"url_patterns":["/portfolio"],"title_keywords":["micro vc","seed fund"],"content_keywords":["pre-seed","micro fund","first check"],"evidence_required":["fund_aum"]}',
 '["aum","check_size_typical","stages","sectors"]',
 '{"urls":[],"search_queries":["micro VC seed fund"]}',
 'briefcase','#8b5cf6'),
('investor_family_office', 'Family Office', 'capital', 'company', 'investor',
 '{"url_patterns":["/about","/family-office"],"title_keywords":["family office","private investment"],"content_keywords":["multi-generational","wealth management","direct investment"],"evidence_required":["family_principal"]}',
 '["family_principal","aum","strategy","sectors"]',
 '{"urls":[],"search_queries":["family office direct investment"]}',
 'home','#a855f7'),
('investor_endowment', 'Endowment', 'capital', 'company', 'investor',
 '{"url_patterns":["/investments"],"title_keywords":["endowment"],"content_keywords":["university endowment","permanent fund"],"evidence_required":["institution_name"]}',
 '["institution_name","aum","allocation_alternatives"]',
 '{"urls":[],"search_queries":["university endowment investments"]}',
 'graduation','#9333ea'),
('investor_sovereign', 'Sovereign Wealth Fund', 'capital', 'company', 'investor',
 '{"url_patterns":["/about"],"title_keywords":["sovereign wealth","SWF"],"content_keywords":["sovereign","state-owned","strategic reserve"],"evidence_required":["country_name"]}',
 '["country_name","aum","strategy","sectors"]',
 '{"urls":[],"search_queries":["sovereign wealth fund investments"]}',
 'flag','#7e22ce'),
('investor_pension', 'Pension Fund', 'capital', 'company', 'investor',
 '{"url_patterns":["/investments"],"title_keywords":["pension","retirement system"],"content_keywords":["beneficiaries","pension liabilities"],"evidence_required":["plan_name"]}',
 '["plan_name","aum","allocation_alternatives"]',
 '{"urls":[],"search_queries":["pension fund alternative investments"]}',
 'shield','#6b21a8'),
('fund_of_funds', 'Fund of Funds', 'capital', 'company', 'investor',
 '{"url_patterns":["/portfolio"],"title_keywords":["fund of funds","FoF"],"content_keywords":["limited partner","commit to funds","manager selection"],"evidence_required":["fund_count_committed"]}',
 '["aum","fund_count_committed","strategy","sectors"]',
 '{"urls":[],"search_queries":["fund of funds LP commitments"]}',
 'layers','#7c3aed'),
('accelerator', 'Accelerator', 'capital', 'company', 'investor',
 '{"url_patterns":["/program","/apply","/batch","/cohort"],"title_keywords":["accelerator","cohort","batch"],"content_keywords":["demo day","cohort","program duration","equity stake"],"evidence_required":["program_duration_weeks"]}',
 '["program_duration_weeks","check_size","equity_taken","cohort_size","sectors"]',
 '{"urls":["https://www.ycombinator.com","https://techstars.com"],"search_queries":["startup accelerator program"]}',
 'rocket','#ec4899'),
('incubator', 'Incubator', 'capital', 'company', 'investor',
 '{"url_patterns":["/incubator","/residency"],"title_keywords":["incubator","residency"],"content_keywords":["incubate","office space","mentorship"],"evidence_required":["program_type"]}',
 '["program_type","duration","sectors","check_size"]',
 '{"urls":[],"search_queries":["startup incubator residency"]}',
 'egg','#f472b6'),
('venture_studio', 'Venture Studio', 'capital', 'company', 'investor',
 '{"url_patterns":["/studio","/build"],"title_keywords":["venture studio","startup studio"],"content_keywords":["build companies","EIR","co-found"],"evidence_required":["studio_model"]}',
 '["studio_model","companies_built","sectors","check_size"]',
 '{"urls":[],"search_queries":["venture studio build companies"]}',
 'wrench','#e879f9'),
('syndicate', 'Syndicate', 'capital', 'company', 'investor',
 '{"url_patterns":["/syndicate","/deal"],"title_keywords":["syndicate"],"content_keywords":["lead investor","SPV","carry","backers"],"evidence_required":["syndicate_lead"]}',
 '["syndicate_lead","backers_count","deal_size","stages"]',
 '{"urls":["https://angel.co/syndicates"],"search_queries":["angel syndicate SPV"]}',
 'users','#d946ef'),
('secondary_buyer', 'Secondary Buyer', 'capital', 'company', 'investor',
 '{"url_patterns":["/secondary"],"title_keywords":["secondary","liquidity"],"content_keywords":["secondary transaction","tender offer","liquidity solution"],"evidence_required":["secondary_strategy"]}',
 '["secondary_strategy","aum","typical_deal_size"]',
 '{"urls":[],"search_queries":["secondary market buyer startups"]}',
 'refresh','#c026d3'),

-- ===== People at firms =====
('firm_person', 'Person at firm', 'operator', 'person', NULL,
 '{"url_patterns":["/team","/people","/about"],"title_keywords":["partner","principal","associate"],"content_keywords":["joined","previously","background"],"evidence_required":["firm_employer"]}',
 '["firm_employer","title","tenure_start","background","education"]', '{}', 'user','#0ea5e9'),
('gp_partner', 'General Partner', 'capital', 'person', 'firm_person',
 '{"url_patterns":["/team","/partners"],"title_keywords":["general partner","managing partner","GP"],"content_keywords":["general partner","co-founded","leads investments"],"evidence_required":["firm_employer"]}',
 '["firm_employer","title","tenure_start","sectors","board_seats"]','{}', 'user-check','#0284c7'),
('principal', 'Principal', 'capital', 'person', 'firm_person',
 '{"url_patterns":["/team"],"title_keywords":["principal"],"content_keywords":["principal at","leads deals","sourcing"],"evidence_required":["firm_employer"]}',
 '["firm_employer","title","tenure_start","sectors"]','{}', 'user','#0369a1'),
('associate', 'Associate', 'capital', 'person', 'firm_person',
 '{"url_patterns":["/team"],"title_keywords":["associate","senior associate"],"content_keywords":["associate at","analyst"],"evidence_required":["firm_employer"]}',
 '["firm_employer","title","tenure_start","sectors"]','{}', 'user','#0c4a6e'),
('scout', 'Scout', 'capital', 'person', 'firm_person',
 '{"url_patterns":["/scouts"],"title_keywords":["scout"],"content_keywords":["scout program","scout investor"],"evidence_required":["scouting_firm"]}',
 '["scouting_firm","check_size","sectors"]','{}', 'binoculars','#06b6d4'),
('venture_partner', 'Venture Partner', 'capital', 'person', 'firm_person',
 '{"url_patterns":["/team"],"title_keywords":["venture partner"],"content_keywords":["venture partner","part-time"],"evidence_required":["firm_employer"]}',
 '["firm_employer","title","sectors","operating_background"]','{}', 'user','#0e7490'),
('operating_partner', 'Operating Partner', 'capital', 'person', 'firm_person',
 '{"url_patterns":["/team"],"title_keywords":["operating partner"],"content_keywords":["operating partner","portfolio support"],"evidence_required":["firm_employer"]}',
 '["firm_employer","function","operating_background"]','{}', 'cog','#155e75'),
('entrepreneur_in_residence', 'Entrepreneur in Residence', 'capital', 'person', 'firm_person',
 '{"url_patterns":["/team","/eir"],"title_keywords":["entrepreneur in residence","EIR"],"content_keywords":["EIR","exploring next","incubating"],"evidence_required":["host_firm"]}',
 '["host_firm","previous_company","sectors_exploring"]','{}', 'lightbulb','#0891b2'),
('advisor', 'Advisor', 'advisory', 'person', NULL,
 '{"url_patterns":["/advisors"],"title_keywords":["advisor","board advisor"],"content_keywords":["advisor to","advisory board"],"evidence_required":["companies_advised"]}',
 '["companies_advised","domain_expertise"]','{}', 'compass','#14b8a6'),

-- ===== Venture partners (non-firm-employee) =====
('lawyer', 'Lawyer', 'legal', 'person', NULL,
 '{"url_patterns":["/attorneys","/lawyers","/people"],"title_keywords":["attorney","esq","JD"],"content_keywords":["bar admission","law school"],"evidence_required":["bar_state OR law_firm_employer"]}',
 '["bar_state","practice_area","law_firm_employer","jd_school","years_practicing"]','{}', 'scale','#dc2626'),
('lawyer_securities', 'Securities Lawyer', 'legal', 'person', 'lawyer',
 '{"url_patterns":["/attorneys","/lawyers","/people"],"title_keywords":["securities","1933 act","1934 act","Rule 144A","Reg D"],"content_keywords":["bar admission","JD","law school","venture financings","fund formation"],"evidence_required":["bar_state OR law_firm_employer","JD_school"]}',
 '["bar_state","practice_area","law_firm_employer","jd_school","years_practicing","reg_d_experience"]','{}', 'scale','#b91c1c'),
('lawyer_corporate', 'Corporate Lawyer', 'legal', 'person', 'lawyer',
 '{"url_patterns":["/attorneys"],"title_keywords":["corporate","M&A","mergers"],"content_keywords":["mergers and acquisitions","corporate governance","financings"],"evidence_required":["bar_state OR law_firm_employer"]}',
 '["bar_state","practice_area","law_firm_employer","ma_deal_count"]','{}', 'scale','#991b1b'),
('lawyer_ip', 'IP Lawyer', 'legal', 'person', 'lawyer',
 '{"url_patterns":["/attorneys"],"title_keywords":["patent","trademark","intellectual property","IP"],"content_keywords":["patent prosecution","trademark","USPTO"],"evidence_required":["bar_state OR uspto_reg"]}',
 '["bar_state","uspto_reg","practice_area","law_firm_employer"]','{}', 'shield','#7f1d1d'),
('lawyer_employment', 'Employment Lawyer', 'legal', 'person', 'lawyer',
 '{"url_patterns":["/attorneys"],"title_keywords":["employment","labor"],"content_keywords":["employment law","wage","discrimination","wrongful termination"],"evidence_required":["bar_state"]}',
 '["bar_state","practice_area","law_firm_employer"]','{}', 'scale','#dc2626'),
('lawyer_immigration', 'Immigration Lawyer', 'legal', 'person', 'lawyer',
 '{"url_patterns":["/attorneys"],"title_keywords":["immigration","visa","H-1B","O-1"],"content_keywords":["visa petitions","green card","immigration matters"],"evidence_required":["bar_state"]}',
 '["bar_state","visa_types","law_firm_employer"]','{}', 'globe','#ef4444'),
('lawyer_tax', 'Tax Lawyer', 'legal', 'person', 'lawyer',
 '{"url_patterns":["/attorneys"],"title_keywords":["tax"],"content_keywords":["tax controversy","tax planning","LLM tax"],"evidence_required":["bar_state OR llm_tax"]}',
 '["bar_state","llm_tax","practice_area","law_firm_employer"]','{}', 'calculator','#f87171'),
('banker_investment', 'Investment Banker', 'financial', 'person', NULL,
 '{"url_patterns":["/team"],"title_keywords":["investment banker","banking"],"content_keywords":["IPO","equity capital markets","DCM","M&A advisory"],"evidence_required":["bank_employer"]}',
 '["bank_employer","title","coverage_sector","deal_history"]','{}', 'briefcase','#0f172a'),
('banker_commercial', 'Commercial Banker', 'financial', 'person', NULL,
 '{"url_patterns":["/team"],"title_keywords":["commercial banker","relationship manager"],"content_keywords":["commercial banking","credit","lending"],"evidence_required":["bank_employer"]}',
 '["bank_employer","title","client_segment"]','{}', 'briefcase','#1e293b'),
('banker_private', 'Private Banker', 'financial', 'person', NULL,
 '{"url_patterns":["/private-bank"],"title_keywords":["private banker","wealth advisor"],"content_keywords":["private banking","high net worth","wealth management"],"evidence_required":["bank_employer"]}',
 '["bank_employer","aum_managed","client_segment"]','{}', 'briefcase','#334155'),
('banker_m_and_a', 'M&A Banker', 'financial', 'person', 'banker_investment',
 '{"url_patterns":["/team"],"title_keywords":["mergers acquisitions","M&A"],"content_keywords":["M&A advisor","sell-side","buy-side"],"evidence_required":["bank_employer"]}',
 '["bank_employer","sector","deal_history"]','{}', 'briefcase','#475569'),
('broker_dealer', 'Broker Dealer', 'financial', 'company', NULL,
 '{"url_patterns":["/about"],"title_keywords":["broker dealer","FINRA"],"content_keywords":["broker-dealer","FINRA member","CRD"],"evidence_required":["finra_crd"]}',
 '["finra_crd","registration_state","services"]','{}', 'briefcase','#64748b'),
('operator_growth', 'Growth Operator', 'operator', 'person', NULL,
 '{"url_patterns":["/about","/bio"],"title_keywords":["head of growth","VP growth","growth"],"content_keywords":["growth","acquisition","activation","retention"],"evidence_required":["companies_worked"]}',
 '["companies_worked","growth_results","function"]','{}', 'trending-up','#22c55e'),
('operator_sales', 'Sales Operator', 'operator', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["VP sales","CRO","head of sales"],"content_keywords":["sales leader","quota","pipeline"],"evidence_required":["companies_worked"]}',
 '["companies_worked","arr_scaled","function"]','{}', 'phone','#16a34a'),
('operator_marketing', 'Marketing Operator', 'operator', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["CMO","VP marketing","head of marketing"],"content_keywords":["marketing leader","brand","demand gen"],"evidence_required":["companies_worked"]}',
 '["companies_worked","function","brands_scaled"]','{}', 'megaphone','#15803d'),
('operator_product', 'Product Operator', 'operator', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["CPO","VP product","head of product"],"content_keywords":["product leader","roadmap","PMF"],"evidence_required":["companies_worked"]}',
 '["companies_worked","products_shipped","function"]','{}', 'box','#166534'),
('operator_engineering', 'Engineering Operator', 'operator', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["CTO","VP engineering"],"content_keywords":["engineering leader","scaled team","architecture"],"evidence_required":["companies_worked"]}',
 '["companies_worked","team_size_scaled","tech_stack"]','{}', 'code','#14532d'),
('fractional_cfo', 'Fractional CFO', 'advisory', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["fractional CFO","interim CFO"],"content_keywords":["fractional","part-time CFO"],"evidence_required":["cfo_experience"]}',
 '["cfo_experience","client_count","industry_focus"]','{}', 'calculator','#0891b2'),
('fractional_cto', 'Fractional CTO', 'advisory', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["fractional CTO","interim CTO"],"content_keywords":["fractional","part-time CTO"],"evidence_required":["cto_experience"]}',
 '["cto_experience","client_count","tech_stack"]','{}', 'code','#0e7490'),
('fractional_coo', 'Fractional COO', 'advisory', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["fractional COO"],"content_keywords":["fractional","part-time COO"],"evidence_required":["coo_experience"]}',
 '["coo_experience","client_count","industry_focus"]','{}', 'cog','#155e75'),
('fractional_cmo', 'Fractional CMO', 'advisory', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["fractional CMO"],"content_keywords":["fractional","part-time CMO"],"evidence_required":["cmo_experience"]}',
 '["cmo_experience","client_count","industry_focus"]','{}', 'megaphone','#164e63'),
('executive_recruiter', 'Executive Recruiter', 'talent', 'person', NULL,
 '{"url_patterns":["/team","/recruiters"],"title_keywords":["executive recruiter","headhunter","talent partner"],"content_keywords":["executive search","C-suite placement","retained search"],"evidence_required":["search_firm"]}',
 '["search_firm","function_focus","industry_focus","placements"]','{}', 'search','#f59e0b'),
('board_member', 'Board Member', 'advisory', 'person', NULL,
 '{"url_patterns":["/board","/leadership"],"title_keywords":["board member","director","board of directors"],"content_keywords":["board director","independent director"],"evidence_required":["board_seats"]}',
 '["board_seats","public_boards","committees"]','{}', 'users','#0d9488'),
('politician_federal', 'Federal Politician', 'policy', 'person', NULL,
 '{"url_patterns":["/representatives","/senators",".gov"],"title_keywords":["senator","representative","congressman"],"content_keywords":["U.S. Senate","House of Representatives","federal"],"evidence_required":["office_held"]}',
 '["office_held","party","state","district","committees"]','{}', 'flag','#1d4ed8'),
('politician_state', 'State Politician', 'policy', 'person', NULL,
 '{"url_patterns":[".state",".gov"],"title_keywords":["state senator","state representative","assemblymember"],"content_keywords":["state legislature"],"evidence_required":["office_held","state"]}',
 '["office_held","party","state","district"]','{}', 'flag','#2563eb'),
('politician_local', 'Local Politician', 'policy', 'person', NULL,
 '{"url_patterns":[".gov","/council","/mayor"],"title_keywords":["mayor","council member","alderman"],"content_keywords":["city council","municipal"],"evidence_required":["office_held","city"]}',
 '["office_held","party","city"]','{}', 'flag','#3b82f6'),
('policy_advisor', 'Policy Advisor', 'policy', 'person', NULL,
 '{"url_patterns":["/staff","/team"],"title_keywords":["policy advisor","chief of staff","legislative director"],"content_keywords":["policy advisor","legislative aide"],"evidence_required":["principal_employer"]}',
 '["principal_employer","policy_areas","tenure_start"]','{}', 'file','#60a5fa'),

-- ===== Founders & employees =====
('founder', 'Founder', 'operator', 'person', NULL,
 '{"url_patterns":["/about","/team"],"title_keywords":["founder","co-founder","CEO"],"content_keywords":["founded","co-founded","started"],"evidence_required":["company_founded"]}',
 '["company_founded","founding_year","prior_companies","education"]','{}', 'flame','#f97316'),
('founder_solo', 'Solo Founder', 'operator', 'person', 'founder',
 '{"url_patterns":["/about"],"title_keywords":["solo founder","founder CEO"],"content_keywords":["sole founder","founded alone"],"evidence_required":["company_founded"]}',
 '["company_founded","founding_year","stage_reached"]','{}', 'user','#ea580c'),
('co_founder', 'Co-Founder', 'operator', 'person', 'founder',
 '{"url_patterns":["/about","/team"],"title_keywords":["co-founder","cofounder"],"content_keywords":["co-founded","along with"],"evidence_required":["company_founded","co_founders"]}',
 '["company_founded","co_founders","role"]','{}', 'users','#c2410c'),
('founding_engineer', 'Founding Engineer', 'operator', 'person', NULL,
 '{"url_patterns":["/team"],"title_keywords":["founding engineer","first engineer"],"content_keywords":["employee #","founding team","first engineer"],"evidence_required":["company_joined"]}',
 '["company_joined","employee_number","tech_stack"]','{}', 'code','#9a3412'),
('founding_designer', 'Founding Designer', 'operator', 'person', NULL,
 '{"url_patterns":["/team"],"title_keywords":["founding designer","head of design"],"content_keywords":["founding designer","first designer"],"evidence_required":["company_joined"]}',
 '["company_joined","employee_number","design_discipline"]','{}', 'pen','#7c2d12'),
('founding_pm', 'Founding PM', 'operator', 'person', NULL,
 '{"url_patterns":["/team"],"title_keywords":["founding PM","founding product"],"content_keywords":["founding product manager","first PM"],"evidence_required":["company_joined"]}',
 '["company_joined","employee_number","products"]','{}', 'box','#fb923c'),
('technical_founder', 'Technical Founder', 'operator', 'person', 'founder',
 '{"url_patterns":["/about"],"title_keywords":["CTO co-founder","technical founder"],"content_keywords":["technical co-founder","CTO and co-founder"],"evidence_required":["company_founded","technical_background"]}',
 '["company_founded","technical_background","education"]','{}', 'code','#facc15'),
('business_founder', 'Business Founder', 'operator', 'person', 'founder',
 '{"url_patterns":["/about"],"title_keywords":["CEO co-founder","business founder"],"content_keywords":["business co-founder","CEO and co-founder"],"evidence_required":["company_founded","business_background"]}',
 '["company_founded","business_background","mba"]','{}', 'briefcase','#fde047'),
('repeat_founder', 'Repeat Founder', 'operator', 'person', 'founder',
 '{"url_patterns":["/about"],"title_keywords":["serial founder","repeat founder"],"content_keywords":["previously founded","prior exits","second-time founder"],"evidence_required":["prior_companies"]}',
 '["prior_companies","prior_exits","current_company"]','{}', 'refresh','#a16207'),
('serial_entrepreneur', 'Serial Entrepreneur', 'operator', 'person', 'founder',
 '{"url_patterns":["/about"],"title_keywords":["serial entrepreneur"],"content_keywords":["serial entrepreneur","multiple companies"],"evidence_required":["prior_companies"]}',
 '["prior_companies","prior_exits"]','{}', 'refresh','#854d0e'),

-- ===== Financial institutions =====
('investment_bank', 'Investment Bank', 'financial', 'company', NULL,
 '{"url_patterns":["/investmentbanking","/about"],"title_keywords":["investment bank"],"content_keywords":["IPO","M&A advisory","capital markets"],"evidence_required":["bank_name"]}',
 '["bank_name","global_offices","aum","deal_history"]','{}', 'building','#1e40af'),
('commercial_bank', 'Commercial Bank', 'financial', 'company', NULL,
 '{"url_patterns":["/business"],"title_keywords":["commercial bank","business banking"],"content_keywords":["commercial lending","business accounts"],"evidence_required":["bank_name"]}',
 '["bank_name","assets","branches"]','{}', 'building','#1d4ed8'),
('private_bank', 'Private Bank', 'financial', 'company', NULL,
 '{"url_patterns":["/private"],"title_keywords":["private bank","private banking"],"content_keywords":["private banking","high net worth","family office services"],"evidence_required":["bank_name"]}',
 '["bank_name","aum","minimum_account"]','{}', 'building','#2563eb'),
('hedge_fund', 'Hedge Fund', 'financial', 'company', NULL,
 '{"url_patterns":["/strategies","/about"],"title_keywords":["hedge fund","capital management"],"content_keywords":["long/short","quant","systematic","fundamental"],"evidence_required":["fund_name"]}',
 '["fund_name","aum","strategy","manager"]','{}', 'trending-up','#3b82f6'),
('asset_manager', 'Asset Manager', 'financial', 'company', NULL,
 '{"url_patterns":["/strategies"],"title_keywords":["asset management","investment management"],"content_keywords":["mutual fund","ETF","institutional"],"evidence_required":["firm_name"]}',
 '["firm_name","aum","strategies"]','{}', 'briefcase','#60a5fa'),
('insurance', 'Insurance', 'financial', 'company', NULL,
 '{"url_patterns":["/insurance"],"title_keywords":["insurance"],"content_keywords":["underwriting","policy","claims","premium"],"evidence_required":["company_name"]}',
 '["company_name","lines","gross_premiums"]','{}', 'shield','#93c5fd'),
('reinsurer', 'Reinsurer', 'financial', 'company', NULL,
 '{"url_patterns":["/reinsurance"],"title_keywords":["reinsurance","reinsurer"],"content_keywords":["reinsurance treaty","catastrophe"],"evidence_required":["company_name"]}',
 '["company_name","lines","gross_premiums"]','{}', 'shield','#bfdbfe'),
('payment_processor', 'Payment Processor', 'financial', 'company', NULL,
 '{"url_patterns":["/payments","/products"],"title_keywords":["payment processor","payments"],"content_keywords":["payment processing","interchange","acquirer"],"evidence_required":["company_name"]}',
 '["company_name","volume_processed","networks"]','{}', 'credit-card','#1e3a8a'),
('custodian', 'Custodian', 'financial', 'company', NULL,
 '{"url_patterns":["/custody"],"title_keywords":["custody","custodian"],"content_keywords":["custody services","safekeeping","institutional custody"],"evidence_required":["company_name"]}',
 '["company_name","assets_under_custody","clients"]','{}', 'lock','#172554'),
('clearinghouse', 'Clearinghouse', 'financial', 'company', NULL,
 '{"url_patterns":["/clearing"],"title_keywords":["clearinghouse","clearing"],"content_keywords":["clearing","settlement","CCP"],"evidence_required":["company_name"]}',
 '["company_name","markets_cleared"]','{}', 'refresh','#020617'),
('exchange_traditional', 'Traditional Exchange', 'financial', 'company', NULL,
 '{"url_patterns":["/markets"],"title_keywords":["stock exchange","exchange"],"content_keywords":["listed","equities","derivatives"],"evidence_required":["exchange_name"]}',
 '["exchange_name","markets","listings_count"]','{}', 'bar-chart','#1e1b4b'),
('exchange_crypto', 'Crypto Exchange', 'financial', 'company', NULL,
 '{"url_patterns":["/trade","/markets"],"title_keywords":["crypto exchange","digital asset"],"content_keywords":["spot trading","derivatives","custody"],"evidence_required":["exchange_name"]}',
 '["exchange_name","markets","daily_volume","custody_model"]','{}', 'bitcoin','#312e81'),

-- ===== Companies =====
('startup_pre_seed', 'Pre-Seed Startup', 'company', 'company', NULL,
 '{"url_patterns":["/about"],"title_keywords":["startup"],"content_keywords":["pre-seed","stealth","early-stage"],"evidence_required":["funding_stage"]}',
 '["funding_stage","team_size","sector","founded_year"]','{}', 'flame','#0284c7'),
('startup_seed', 'Seed Startup', 'company', 'company', NULL,
 '{"url_patterns":["/about"],"title_keywords":["startup"],"content_keywords":["seed round","seed funding"],"evidence_required":["funding_stage"]}',
 '["funding_stage","team_size","arr","sector"]','{}', 'flame','#0369a1'),
('startup_series_a', 'Series A Startup', 'company', 'company', NULL,
 '{"url_patterns":["/about","/press"],"title_keywords":["raised"],"content_keywords":["Series A","Series A funding"],"evidence_required":["funding_stage"]}',
 '["funding_stage","team_size","arr","sector"]','{}', 'rocket','#0c4a6e'),
('startup_growth', 'Growth Startup', 'company', 'company', NULL,
 '{"url_patterns":["/about","/press"],"title_keywords":["scale","growth"],"content_keywords":["Series B","Series C","growth round"],"evidence_required":["funding_stage"]}',
 '["funding_stage","team_size","arr","sector"]','{}', 'rocket','#082f49'),
('startup_late_stage', 'Late Stage Startup', 'company', 'company', NULL,
 '{"url_patterns":["/about"],"title_keywords":["unicorn","late stage"],"content_keywords":["Series D","Series E","pre-IPO"],"evidence_required":["funding_stage","valuation"]}',
 '["funding_stage","valuation","arr","sector"]','{}', 'rocket','#020617'),
('public_company', 'Public Company', 'company', 'company', NULL,
 '{"url_patterns":["/investors","/ir"],"title_keywords":["NYSE","NASDAQ"],"content_keywords":["ticker","SEC filings","quarterly earnings"],"evidence_required":["ticker"]}',
 '["ticker","exchange","market_cap","revenue"]','{}', 'bar-chart','#1e293b'),
('sme', 'SME', 'company', 'company', NULL,
 '{"url_patterns":["/about"],"title_keywords":[],"content_keywords":["small business","SME","family-owned"],"evidence_required":["employee_count"]}',
 '["employee_count","revenue","industry","founded_year"]','{}', 'building','#334155'),
('enterprise', 'Enterprise', 'company', 'company', NULL,
 '{"url_patterns":["/about"],"title_keywords":["Fortune"],"content_keywords":["enterprise","global","Fortune 500"],"evidence_required":["employee_count"]}',
 '["employee_count","revenue","industry","global_presence"]','{}', 'building','#475569'),
('portfolio_company', 'Portfolio Company', 'company', 'company', NULL,
 '{"url_patterns":["/portfolio"],"title_keywords":[],"content_keywords":["portfolio company","backed by"],"evidence_required":["parent_investor"]}',
 '["parent_investor","stage","sector"]','{}', 'box','#64748b'),
('target_customer_b2b', 'B2B Target Customer', 'company', 'company', NULL,
 '{"url_patterns":["/about","/products"],"title_keywords":[],"content_keywords":["enterprise","B2B"],"evidence_required":["icp_signals"]}',
 '["icp_signals","industry","employee_count","tech_stack"]','{}', 'target','#94a3b8'),
('target_customer_b2c', 'B2C Target Customer', 'company', 'company', NULL,
 '{"url_patterns":["/about"],"title_keywords":[],"content_keywords":["consumer","B2C"],"evidence_required":["icp_signals"]}',
 '["icp_signals","consumer_segment","geography"]','{}', 'target','#cbd5e1'),
('acquirer_strategic', 'Strategic Acquirer', 'company', 'company', NULL,
 '{"url_patterns":["/acquisitions","/press"],"title_keywords":["acquired","acquisition"],"content_keywords":["completed acquisition","strategic acquirer"],"evidence_required":["acquisition_history"]}',
 '["acquisition_history","sectors_acquired","deal_size_typical"]','{}', 'merge','#e2e8f0'),

-- ===== Service firms =====
('law_firm', 'Law Firm', 'service_firm', 'company', NULL,
 '{"url_patterns":["/attorneys","/practices"],"title_keywords":["LLP","law firm","attorneys"],"content_keywords":["practice areas","partners","associates"],"evidence_required":["firm_name"]}',
 '["firm_name","attorney_count","practice_areas","offices"]','{}', 'scale','#b91c1c'),
('accounting_firm', 'Accounting Firm', 'service_firm', 'company', NULL,
 '{"url_patterns":["/services"],"title_keywords":["CPA","accounting"],"content_keywords":["audit","tax","advisory","CPA firm"],"evidence_required":["firm_name"]}',
 '["firm_name","cpa_count","services","offices"]','{}', 'calculator','#dc2626'),
('consulting_firm', 'Consulting Firm', 'service_firm', 'company', NULL,
 '{"url_patterns":["/about","/services"],"title_keywords":["consulting","advisory"],"content_keywords":["strategy consulting","management consulting"],"evidence_required":["firm_name"]}',
 '["firm_name","consultant_count","practice_areas"]','{}', 'compass','#ef4444'),
('executive_search_firm', 'Executive Search Firm', 'service_firm', 'company', NULL,
 '{"url_patterns":["/recruiters","/team"],"title_keywords":["executive search","retained search"],"content_keywords":["executive search","C-suite placements","retained search firm"],"evidence_required":["firm_name"]}',
 '["firm_name","function_focus","industry_focus","placements"]','{}', 'search','#f87171'),
('pr_firm', 'PR Firm', 'service_firm', 'company', NULL,
 '{"url_patterns":["/services"],"title_keywords":["PR","public relations","communications"],"content_keywords":["press relations","media outreach","PR agency"],"evidence_required":["firm_name"]}',
 '["firm_name","clients","industries"]','{}', 'megaphone','#fb7185'),
('marketing_agency', 'Marketing Agency', 'service_firm', 'company', NULL,
 '{"url_patterns":["/services"],"title_keywords":["marketing agency","digital marketing"],"content_keywords":["paid media","content marketing","SEO"],"evidence_required":["firm_name"]}',
 '["firm_name","services","clients"]','{}', 'megaphone','#f43f5e'),
('design_agency', 'Design Agency', 'service_firm', 'company', NULL,
 '{"url_patterns":["/work","/portfolio"],"title_keywords":["design studio","design agency"],"content_keywords":["brand identity","product design","UX"],"evidence_required":["firm_name"]}',
 '["firm_name","disciplines","portfolio"]','{}', 'pen','#e11d48'),
('dev_shop', 'Dev Shop', 'service_firm', 'company', NULL,
 '{"url_patterns":["/services","/portfolio"],"title_keywords":["software development","dev shop"],"content_keywords":["custom software","development services"],"evidence_required":["firm_name"]}',
 '["firm_name","tech_stack","clients"]','{}', 'code','#be123c'),

-- ===== Influence & press =====
('journalist_business', 'Business Journalist', 'press', 'person', NULL,
 '{"url_patterns":["/author","/contributors"],"title_keywords":["reporter","correspondent","staff writer"],"content_keywords":["covers","business reporter"],"evidence_required":["publication"]}',
 '["publication","beats","articles_count","contact"]','{}', 'newspaper','#0f766e'),
('journalist_tech', 'Tech Journalist', 'press', 'person', 'journalist_business',
 '{"url_patterns":["/author"],"title_keywords":["reporter","writer","editor"],"content_keywords":["tech reporter","covers startups"],"evidence_required":["publication"]}',
 '["publication","beats","articles_count"]','{}', 'newspaper','#0d9488'),
('journalist_crypto', 'Crypto Journalist', 'press', 'person', 'journalist_business',
 '{"url_patterns":["/author"],"title_keywords":["reporter","writer"],"content_keywords":["crypto reporter","blockchain reporter"],"evidence_required":["publication"]}',
 '["publication","beats","articles_count"]','{}', 'newspaper','#14b8a6'),
('analyst_industry', 'Industry Analyst', 'press', 'person', NULL,
 '{"url_patterns":["/analysts","/team"],"title_keywords":["analyst","principal analyst"],"content_keywords":["industry analyst","research analyst","Gartner","Forrester","IDC"],"evidence_required":["firm_name"]}',
 '["firm_name","coverage_areas","research_published"]','{}', 'chart-pie','#2dd4bf'),
('podcast_host', 'Podcast Host', 'press', 'person', NULL,
 '{"url_patterns":["/podcast","/episodes"],"title_keywords":["podcast","host"],"content_keywords":["podcast host","episode"],"evidence_required":["podcast_name"]}',
 '["podcast_name","episode_count","topics"]','{}', 'mic','#5eead4'),
('newsletter_writer', 'Newsletter Writer', 'press', 'person', NULL,
 '{"url_patterns":["/newsletter","/substack"],"title_keywords":["newsletter","weekly"],"content_keywords":["subscribers","substack","newsletter"],"evidence_required":["newsletter_name"]}',
 '["newsletter_name","subscribers","topics"]','{}', 'mail','#99f6e4'),
('youtuber_business', 'Business YouTuber', 'press', 'person', NULL,
 '{"url_patterns":["youtube.com/"],"title_keywords":["youtube","channel"],"content_keywords":["subscribers","views","channel"],"evidence_required":["channel_url"]}',
 '["channel_url","subscribers","topics"]','{}', 'video','#ccfbf1'),
('thought_leader', 'Thought Leader', 'press', 'person', NULL,
 '{"url_patterns":["/about"],"title_keywords":["author","speaker"],"content_keywords":["keynote","best-selling","thought leader"],"evidence_required":["public_works"]}',
 '["public_works","books","speaking_topics"]','{}', 'lightbulb','#f0fdfa'),
('conference_organizer', 'Conference Organizer', 'press', 'company', NULL,
 '{"url_patterns":["/event","/conference"],"title_keywords":["conference","summit"],"content_keywords":["annual conference","attendees","speakers"],"evidence_required":["event_name"]}',
 '["event_name","frequency","attendees","focus"]','{}', 'calendar','#ecfeff'),

-- ===== Academic & deep tech =====
('professor', 'Professor', 'academic', 'person', NULL,
 '{"url_patterns":[".edu","/faculty","/people"],"title_keywords":["professor","assistant professor","associate professor"],"content_keywords":["faculty","department of","Ph.D."],"evidence_required":["university"]}',
 '["university","department","research_areas","publications"]','{}', 'graduation','#7c3aed'),
('postdoc', 'Postdoc', 'academic', 'person', NULL,
 '{"url_patterns":[".edu","/lab"],"title_keywords":["postdoc","postdoctoral"],"content_keywords":["postdoctoral researcher","postdoctoral fellow"],"evidence_required":["university","advisor"]}',
 '["university","advisor","research_areas"]','{}', 'graduation','#8b5cf6'),
('phd_student', 'PhD Student', 'academic', 'person', NULL,
 '{"url_patterns":[".edu"],"title_keywords":["PhD student","doctoral candidate"],"content_keywords":["Ph.D. candidate","doctoral student"],"evidence_required":["university","advisor"]}',
 '["university","advisor","research_areas","expected_year"]','{}', 'graduation','#a78bfa'),
('research_scientist', 'Research Scientist', 'academic', 'person', NULL,
 '{"url_patterns":["/research","/about"],"title_keywords":["research scientist","scientist"],"content_keywords":["research scientist","industrial research"],"evidence_required":["employer"]}',
 '["employer","research_areas","publications"]','{}', 'beaker','#c4b5fd'),
('lab_principal_investigator', 'Lab PI', 'academic', 'person', NULL,
 '{"url_patterns":["/lab",".edu"],"title_keywords":["principal investigator","PI","lab director"],"content_keywords":["principal investigator","lab leader"],"evidence_required":["lab_name"]}',
 '["lab_name","institution","research_areas","funding"]','{}', 'beaker','#ddd6fe'),
('technology_transfer_officer', 'Tech Transfer Officer', 'academic', 'person', NULL,
 '{"url_patterns":["/tech-transfer","/ott"],"title_keywords":["technology transfer","licensing officer"],"content_keywords":["technology transfer","licensing","spinout"],"evidence_required":["institution"]}',
 '["institution","deals_closed","sectors"]','{}', 'arrows-right-left','#ede9fe'),
('patent_agent', 'Patent Agent', 'academic', 'person', NULL,
 '{"url_patterns":["/attorneys"],"title_keywords":["patent agent"],"content_keywords":["patent prosecution","USPTO registered"],"evidence_required":["uspto_reg"]}',
 '["uspto_reg","practice_area","firm"]','{}', 'shield','#f5f3ff'),

-- ===== Public sector =====
('government_agency_federal', 'Federal Agency', 'public_sector', 'company', NULL,
 '{"url_patterns":[".gov"],"title_keywords":["department of","agency","administration"],"content_keywords":["federal","U.S. government"],"evidence_required":["agency_name"]}',
 '["agency_name","budget","mission","key_programs"]','{}', 'flag','#1d4ed8'),
('government_agency_state', 'State Agency', 'public_sector', 'company', NULL,
 '{"url_patterns":[".gov","state."],"title_keywords":["state of","department"],"content_keywords":["state agency","department of"],"evidence_required":["agency_name","state"]}',
 '["agency_name","state","budget","mission"]','{}', 'flag','#2563eb'),
('government_agency_local', 'Local Agency', 'public_sector', 'company', NULL,
 '{"url_patterns":[".gov"],"title_keywords":["city of","county"],"content_keywords":["municipal","city","county"],"evidence_required":["agency_name"]}',
 '["agency_name","jurisdiction","mission"]','{}', 'flag','#3b82f6'),
('multilateral_org', 'Multilateral Organization', 'public_sector', 'company', NULL,
 '{"url_patterns":[".org",".int"],"title_keywords":["United Nations","World Bank","IMF","WHO"],"content_keywords":["multilateral","international organization"],"evidence_required":["org_name"]}',
 '["org_name","member_countries","mission"]','{}', 'globe','#60a5fa'),
('ngo', 'NGO', 'public_sector', 'company', NULL,
 '{"url_patterns":[".org"],"title_keywords":["foundation","NGO","nonprofit"],"content_keywords":["nonprofit","501c3","mission"],"evidence_required":["org_name"]}',
 '["org_name","mission","programs","budget"]','{}', 'heart','#93c5fd'),
('think_tank', 'Think Tank', 'public_sector', 'company', NULL,
 '{"url_patterns":[".org","/research"],"title_keywords":["institute","center for"],"content_keywords":["think tank","policy research","policy briefs"],"evidence_required":["org_name"]}',
 '["org_name","research_areas","scholars","publications"]','{}', 'lightbulb','#bfdbfe');
