-- Task #3: seed the VC Source Registry with ~150 public, free sources
-- across five tiers. Idempotent via INSERT OR REPLACE on the
-- UNIQUE (authority, source_name) pair declared in 347_vc_sources.sql.
--
-- Priority tiers:
--   100  Tier S - US federal      (SEC/IRS — exhaustive, authoritative)
--    90  Tier S - US state        (state pension PE/private-credit reports)
--    85  Tier S - international   (UK/SG/IL/CN/IN/CA/HK/EU national regulators)
--    70  Tier A - industry assoc + endowments + SWFs (annual reports)
--    40  Tier B - press wires + tech/regional press (signal, not authority)
--    20  Tier C - accelerator cohorts + conference/podcast directories

-- ============================================================
-- Tier S — US Federal (SEC EDGAR + IRS)
-- ============================================================
INSERT OR REPLACE INTO vc_sources (id, jurisdiction, authority, data_type, source_name, base_url, access_pattern, refresh_cadence, authentication, auth_notes, historical_depth, data_fields_json, seed_url_template, enabled, priority) VALUES
 ('src_sec_form_adv','us-federal','SEC','fund_registration','Form ADV','https://adviserinfo.sec.gov','json_api','quarterly','user_agent','SEC requires descriptive User-Agent header (org + contact email)','since 2001','["firm_name","crd_number","aum_usd","gp_persons","employee_count","fee_structure","custodian","auditor","disciplinary_history","control_persons","wrap_fee_programs","minimum_account_size","hq_address","other_offices","website"]','https://adviserinfo.sec.gov/firm/summary/{crd}',1,100),
 ('src_sec_form_d','us-federal','SEC','private_placement','Form D','https://efts.sec.gov/LATEST/search-index?forms=D','json_api','daily','user_agent','EDGAR full-text search API; rate-limit ~10 req/s','since 2008','["issuer_name","total_offering_amount","sold_amount","investor_count","minimum_investment","industry_group","exemption_claimed","related_persons","date_of_first_sale"]','https://efts.sec.gov/LATEST/search-index?forms=D&dateRange=custom&startdt={start}&enddt={end}',1,100),
 ('src_sec_form_13f','us-federal','SEC','institutional_holdings','Form 13F','https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&type=13F','xml_feed','quarterly','user_agent','45-day filing window after quarter end','since 1979','["filer_name","cik","period","holdings","shares_held","market_value_usd","put_call","investment_discretion","voting_authority"]','https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK={cik}&type=13F',1,100),
 ('src_sec_sched_13d','us-federal','SEC','beneficial_ownership','Schedule 13D','https://efts.sec.gov/LATEST/search-index?forms=SC%2013D','json_api','daily','user_agent',NULL,'since 1968','["reporting_person","issuer","shares_owned","percent_class","date_of_event","source_of_funds","purpose_of_transaction","contracts_arrangements"]','https://efts.sec.gov/LATEST/search-index?forms=SC%2013D&ciks={cik}',1,100),
 ('src_sec_sched_13g','us-federal','SEC','beneficial_ownership','Schedule 13G','https://efts.sec.gov/LATEST/search-index?forms=SC%2013G','json_api','daily','user_agent','Passive holders, >5% threshold','since 1977','["reporting_person","issuer","shares_owned","percent_class","date_of_event"]','https://efts.sec.gov/LATEST/search-index?forms=SC%2013G&ciks={cik}',1,100),
 ('src_sec_form_4','us-federal','SEC','beneficial_ownership','Form 4','https://efts.sec.gov/LATEST/search-index?forms=4','json_api','daily','user_agent','Insider transactions; 2-day filing window','since 2003','["reporting_owner","issuer","transaction_date","transaction_code","shares","price_per_share","ownership_after"]','https://efts.sec.gov/LATEST/search-index?forms=4&ciks={cik}',1,100),
 ('src_sec_form_s1','us-federal','SEC','ipo_filing','Form S-1','https://efts.sec.gov/LATEST/search-index?forms=S-1','json_api','daily','user_agent',NULL,'since 1994','["issuer","filing_date","shares_offered","price_range","underwriters","risk_factors","use_of_proceeds","principal_shareholders","exec_compensation","prior_financing_rounds"]','https://efts.sec.gov/LATEST/search-index?forms=S-1&ciks={cik}',1,100),
 ('src_sec_form_8k','us-federal','SEC','material_event','Form 8-K','https://efts.sec.gov/LATEST/search-index?forms=8-K','json_api','hourly','user_agent','4-business-day filing window for most items','since 1994','["filer","cik","event_date","item_codes","exhibits","press_release"]','https://efts.sec.gov/LATEST/search-index?forms=8-K&ciks={cik}',1,100),
 ('src_sec_form_10k','us-federal','SEC','annual_report_company','Form 10-K','https://efts.sec.gov/LATEST/search-index?forms=10-K','json_api','quarterly','user_agent',NULL,'since 1994','["filer","fiscal_year","revenue","net_income","balance_sheet","cash_flow","mdna","risk_factors","executive_compensation","related_party_transactions","subsidiaries"]','https://efts.sec.gov/LATEST/search-index?forms=10-K&ciks={cik}',1,100),
 ('src_sec_form_10q','us-federal','SEC','quarterly_report_company','Form 10-Q','https://efts.sec.gov/LATEST/search-index?forms=10-Q','json_api','quarterly','user_agent',NULL,'since 1994','["filer","period","revenue","net_income","balance_sheet","cash_flow"]','https://efts.sec.gov/LATEST/search-index?forms=10-Q&ciks={cik}',1,100),
 ('src_sec_form_adv_e','us-federal','SEC','fund_registration','Form ADV-E','https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&type=ADV-E','xml_feed','annually','user_agent','Independent verification of custody','since 2010','["firm","crd","auditor","period","exceptions"]',NULL,1,100),
 ('src_irs_form_990','us-federal','IRS','nonprofit_filing','Form 990','https://apps.irs.gov/app/eos/','html_scrape','annually','user_agent','Tax-Exempt Organization Search; PDFs back to 2001','since 2001','["org_name","ein","gross_receipts","total_assets","investments","officers_compensation","independent_contractors","grants_paid","program_expenses","investment_managers"]','https://apps.irs.gov/app/eos/detailsPage?ein={ein}',1,100);

-- ============================================================
-- Tier S — US State pension funds (LP holdings + private-equity programs)
-- ============================================================
INSERT OR REPLACE INTO vc_sources (id, jurisdiction, authority, data_type, source_name, base_url, access_pattern, refresh_cadence, authentication, historical_depth, data_fields_json, enabled, priority) VALUES
 ('src_pen_calpers','us-state-ca','CalPERS','pension_holdings','CalPERS Private Equity Program','https://www.calpers.ca.gov/page/investments/asset-classes/private-equity','pdf_download','quarterly','none','since 1998','["fund_name","gp","vintage","commitment_usd","cash_in","cash_out","nav","since_inception_irr","tvpi","dpi"]',1,90),
 ('src_pen_calstrs','us-state-ca','CalSTRS','pension_holdings','CalSTRS Private Equity Portfolio','https://www.calstrs.com/files/private-equity-portfolio-performance','pdf_download','quarterly','none','since 1988','["fund_name","gp","vintage","commitment_usd","contributed","distributed","nav","net_irr"]',1,90),
 ('src_pen_opers','us-state-oh','OPERS','pension_holdings','Ohio PERS Private Equity Holdings','https://www.opers.org/investments/','pdf_download','quarterly','none','rolling 10y','["fund_name","gp","commitment_usd","vintage","nav","irr"]',1,90),
 ('src_pen_nyscrf','us-state-ny','NYSCRF','pension_holdings','NY State Common Retirement Fund — Private Equity','https://www.osc.ny.gov/common-retirement-fund/investments/private-equity','html_scrape','quarterly','none','since 1985','["fund_name","gp","vintage","commitment_usd","nav","strategy"]',1,90),
 ('src_pen_wasib','us-state-wa','WSIB','pension_holdings','Washington State Investment Board PE Annual Report','https://www.sib.wa.gov/investments/private-equity','pdf_download','annually','none','since 1981','["fund_name","gp","vintage","commitment_usd","cash_flows","nav","irr","tvpi"]',1,90),
 ('src_pen_oregon','us-state-or','Oregon Treasury','pension_holdings','Oregon PERF — Alternatives','https://www.oregon.gov/treasury/invested-for-oregon/Pages/Alternatives-Portfolio.aspx','pdf_download','quarterly','none','since 1981','["fund_name","gp","commitment_usd","contributed","distributed","nav","net_irr"]',1,90),
 ('src_pen_texas_trs','us-state-tx','TRS Texas','pension_holdings','Teacher Retirement System of Texas — Private Equity','https://www.trs.texas.gov/Pages/about_publications_investment.aspx','pdf_download','quarterly','none','since 1995','["fund_name","gp","commitment_usd","contributed","distributed","nav","irr"]',1,90),
 ('src_pen_swib','us-state-wi','SWIB','pension_holdings','Wisconsin Investment Board — Private Markets','https://www.swib.state.wi.us/our-investments','pdf_download','annually','none','since 1985','["fund_name","gp","commitment_usd","vintage","strategy","nav","irr"]',1,90),
 ('src_pen_prim','us-state-ma','MassPRIM','pension_holdings','Massachusetts PRIT — Private Equity','https://www.mapension.com/investments','pdf_download','quarterly','none','since 1990','["fund_name","gp","commitment_usd","contributed","distributed","nav","irr"]',1,90),
 ('src_pen_ncrsd','us-state-nc','NC Treasurer','pension_holdings','NC Retirement Systems — Alternatives','https://www.nctreasurer.com/divisions/investment-management/portfolio-performance','pdf_download','quarterly','none','since 1990','["fund_name","gp","commitment_usd","strategy","nav","irr"]',1,90),
 ('src_pen_nj','us-state-nj','NJ DOI','pension_holdings','NJ Division of Investment — Alternatives','https://www.state.nj.us/treasury/doinvest/alternativeinvestments.shtml','pdf_download','quarterly','none','since 2005','["fund_name","gp","commitment_usd","contributed","distributed","nav","irr"]',1,90),
 ('src_pen_imrf','us-state-il','IMRF','pension_holdings','Illinois Municipal Retirement Fund — Alternatives','https://www.imrf.org/en/about-imrf/investments','pdf_download','quarterly','none','since 1990','["fund_name","gp","commitment_usd","vintage","nav","irr"]',1,90),
 ('src_pen_vrs','us-state-va','VRS','pension_holdings','Virginia Retirement System — Private Investment Partnerships','https://www.varetire.org/about/investments/','pdf_download','annually','none','since 1989','["fund_name","gp","vintage","commitment_usd","nav","irr","tvpi"]',1,90),
 ('src_pen_fsba','us-state-fl','Florida SBA','pension_holdings','Florida SBA — Private Equity','https://www.sbafla.com/fsb/InvestmentReports.aspx','pdf_download','quarterly','none','since 1989','["fund_name","gp","commitment_usd","contributed","distributed","nav","irr","tvpi"]',1,90),
 ('src_pen_mi_ors','us-state-mi','Michigan ORS','pension_holdings','Michigan Treasury — Alternatives','https://www.michigan.gov/treasury/about/divisions/Investments','pdf_download','quarterly','none','since 1989','["fund_name","gp","commitment_usd","nav","irr"]',1,90),
 ('src_pen_psers','us-state-pa','PSERS PA','pension_holdings','PA PSERS — Private Equity','https://www.psers.pa.gov/About/Investment/Pages/Performance.aspx','pdf_download','quarterly','none','since 1985','["fund_name","gp","commitment_usd","vintage","nav","irr"]',1,90),
 ('src_pen_ct_ott','us-state-ct','CT Treasurer','pension_holdings','Connecticut Retirement Plans — Private Investment Fund','https://portal.ct.gov/OTT/Pension-Funds/Connecticut-Retirement-Plans-and-Trust-Funds-CRPTF','pdf_download','quarterly','none','since 1987','["fund_name","gp","commitment_usd","nav","irr"]',1,90),
 ('src_pen_md_srps','us-state-md','MSRA','pension_holdings','Maryland State Retirement Agency — Private Equity','https://sra.maryland.gov/investment-overview','pdf_download','annually','none','since 1989','["fund_name","gp","commitment_usd","vintage","nav","irr"]',1,90),
 ('src_pen_mn_sbi','us-state-mn','Minnesota SBI','pension_holdings','Minnesota State Board of Investment — Private Markets','https://mn.gov/sbi/investments/portfolio/','pdf_download','quarterly','none','since 1985','["fund_name","gp","commitment_usd","vintage","strategy","nav","irr"]',1,90),
 ('src_pen_co_pera','us-state-co','Colorado PERA','pension_holdings','Colorado PERA — Private Equity','https://www.copera.org/investments/portfolio-statistics','pdf_download','quarterly','none','since 1991','["fund_name","gp","commitment_usd","nav","irr"]',1,90),
 ('src_pen_az_srs','us-state-az','ASRS','pension_holdings','Arizona State Retirement System — Private Equity','https://www.azasrs.gov/content/investments','pdf_download','annually','none','since 2005','["fund_name","gp","commitment_usd","nav","irr"]',1,90),
 ('src_pen_tn_tcrs','us-state-tn','Tennessee Treasury','pension_holdings','TCRS — Private Equity','https://treasury.tn.gov/Retirement/Information-and-Resources/Investment-Information','pdf_download','annually','none','since 2010','["fund_name","gp","commitment_usd","nav","irr"]',1,90);

-- ============================================================
-- Tier S — International regulators (corporate + fund registries)
-- ============================================================
INSERT OR REPLACE INTO vc_sources (id, jurisdiction, authority, data_type, source_name, base_url, access_pattern, refresh_cadence, authentication, historical_depth, data_fields_json, seed_url_template, enabled, priority) VALUES
 ('src_uk_ch','uk','Companies House','corporate_registry','UK Companies House','https://find-and-update.company-information.service.gov.uk','json_api','daily','none','since 1844','["company_number","name","status","incorporation_date","officers","persons_with_significant_control","filings","sic_codes","accounts_filed","share_capital"]','https://api.company-information.service.gov.uk/company/{company_number}',1,85),
 ('src_uk_fca','uk','FCA','fund_registration','FCA Financial Services Register','https://register.fca.org.uk','json_api','daily','api_key','since 2001','["firm_name","fca_reference","permissions","approved_persons","appointed_representatives","status","trading_names","disciplinary_history"]','https://register.fca.org.uk/services/V0.1/Firm/{frn}',1,85),
 ('src_sg_mas','sg','MAS','fund_registration','Singapore MAS Financial Institutions Directory','https://eservices.mas.gov.sg/fid','html_scrape','weekly','none','since 2000','["institution_name","institution_type","license_type","regulatory_status","representatives"]',NULL,1,85),
 ('src_sg_acra','sg','ACRA','corporate_registry','Singapore ACRA BizFile+','https://www.bizfile.gov.sg','html_scrape','daily','none','since 1967','["uen","entity_name","entity_status","incorporation_date","registered_office","directors","shareholders","activities","share_capital"]','https://www.bizfile.gov.sg/ngbbizfileinternet/faces/oracle/webcenter/portalapp/pages/BizfileSearchPage.jspx?uen={uen}',1,85),
 ('src_il_isa','il','ISA','fund_registration','Israel Securities Authority — Magna','https://www.magna.isa.gov.il','html_scrape','daily','none','since 2000','["filer","license","filings","officers","disclosures"]',NULL,1,85),
 ('src_cn_amac','cn','AMAC','fund_registration','China AMAC Private Fund Manager Registry','https://gs.amac.org.cn','html_scrape','weekly','none','since 2014','["manager_name","manager_id","fund_type","registered_capital","aum_cny","legal_rep","key_personnel"]',NULL,1,85),
 ('src_in_sebi','in','SEBI','fund_registration','SEBI Alternative Investment Funds Register','https://www.sebi.gov.in/intermediaries.html','html_scrape','weekly','none','since 2012','["aif_name","registration_number","category","fund_manager","corpus_inr"]',NULL,1,85),
 ('src_in_mca','in','MCA21','corporate_registry','India Ministry of Corporate Affairs (MCA21)','https://www.mca.gov.in','html_scrape','daily','login','since 1956','["cin","company_name","status","incorporation_date","directors","din_holders","authorized_capital","paid_up_capital","registered_office"]',NULL,1,85),
 ('src_ca_csa','ca','CSA','fund_registration','Canadian Securities Administrators — National Registration Search','https://www.securities-administrators.ca/nrs/nrsearch.aspx','html_scrape','daily','none','since 2009','["firm_name","ncrd","registration_category","registered_jurisdictions","sponsoring_firm"]',NULL,1,85),
 ('src_hk_sfc','hk','SFC','fund_registration','Hong Kong SFC Public Register','https://www.sfc.hk/publicregWeb','html_scrape','daily','none','since 2003','["entity_name","ce_number","regulated_activities","responsible_officers","conditions"]',NULL,1,85),
 ('src_eu_esma','eu','ESMA','fund_registration','ESMA Registers (AIFMs, UCITS, MiFID)','https://registers.esma.europa.eu','json_api','daily','none','since 2014','["entity_name","lei","home_state","passport_states","entity_type","status"]',NULL,1,85),
 ('src_eu_de_bafin','eu-de','BaFin','fund_registration','Germany BaFin Company Database','https://portal.mvp.bafin.de','html_scrape','daily','none','since 2002','["firm_name","bafin_id","license_type","status"]',NULL,1,85),
 ('src_eu_fr_amf','eu-fr','AMF','fund_registration','France AMF GECO Register','https://geco.amf-france.org','html_scrape','daily','none','since 2003','["entity_name","amf_id","entity_type","status","funds_managed"]',NULL,1,85),
 ('src_eu_it_consob','eu-it','CONSOB','fund_registration','Italy CONSOB Register of Intermediaries','https://www.consob.it/web/area-pubblica/albo','html_scrape','weekly','none','since 1998','["intermediary_name","consob_number","authorization","activities"]',NULL,1,85),
 ('src_eu_es_cnmv','eu-es','CNMV','fund_registration','Spain CNMV Public Register','https://www.cnmv.es/portal/consultas/MostrarListados.aspx','html_scrape','weekly','none','since 1988','["entity_name","cnmv_number","entity_type","authorized_activities"]',NULL,1,85),
 ('src_au_asic','au','ASIC','corporate_registry','Australia ASIC Connect','https://connectonline.asic.gov.au','html_scrape','daily','none','since 1991','["acn","abn","company_name","status","officeholders","share_structure","registered_office"]',NULL,1,85),
 ('src_eu_nl_afm','eu-nl','AFM','fund_registration','Netherlands AFM Register','https://www.afm.nl/en/professionals/registers','html_scrape','daily','none','since 2002','["firm_name","afm_id","license","status"]',NULL,1,85),
 ('src_eu_se_fi','eu-se','Finansinspektionen','fund_registration','Sweden Finansinspektionen Company Register','https://www.fi.se/en/our-registers/company-register/','json_api','daily','none','since 2003','["firm_name","fi_id","permissions","status"]',NULL,1,85),
 ('src_eu_be_fsma','eu-be','FSMA','fund_registration','Belgium FSMA Registers','https://www.fsma.be/en/registers','html_scrape','weekly','none','since 2011','["entity_name","fsma_id","activity","status"]',NULL,1,85);

-- ============================================================
-- Tier A — Industry associations + Crunchbase/AngelList + endowments + SWFs
-- ============================================================
INSERT OR REPLACE INTO vc_sources (id, jurisdiction, authority, data_type, source_name, base_url, access_pattern, refresh_cadence, authentication, historical_depth, data_fields_json, enabled, priority) VALUES
 ('src_assoc_nvca','us-federal','NVCA','industry_association','NVCA Member Directory + Yearbook','https://nvca.org/membership/members/','html_scrape','annually','none','since 1973','["member_name","website","hq","fund_focus","aum_usd","portfolio_count"]',1,70),
 ('src_assoc_evca','eu','Invest Europe','industry_association','Invest Europe Member Directory','https://www.investeurope.eu/about-us/our-members/','html_scrape','annually','none','since 1983','["member_name","country","aum_eur","strategy","website"]',1,70),
 ('src_assoc_bvca','uk','BVCA','industry_association','BVCA Member Directory','https://www.bvca.co.uk/membership/find-a-member','html_scrape','annually','none','since 1983','["member_name","strategy","fund_focus","aum_gbp","website"]',1,70),
 ('src_crunchbase_org','global','Crunchbase','startup_database','Crunchbase Public Organization Pages','https://www.crunchbase.com/organization','html_scrape','daily','none','since 2007','["org_name","short_description","founded","hq","funding_total","funding_rounds","investors","categories","employee_range","website","social_handles"]',1,70),
 ('src_angellist_synd','global','AngelList','startup_database','AngelList Public Syndicates','https://www.angellist.com/syndicates','html_scrape','weekly','none','since 2013','["syndicate_name","lead","backing","investment_count","focus","deal_history"]',1,70);

-- Tier A — Endowments (~30 universities)
INSERT OR REPLACE INTO vc_sources (id, jurisdiction, authority, data_type, source_name, base_url, access_pattern, refresh_cadence, authentication, historical_depth, data_fields_json, enabled, priority) VALUES
 ('src_endow_harvard','global','Harvard','endowment_holdings','Harvard Management Company Annual Report','https://www.hmc.harvard.edu/content/HMC-Annual-Reports','pdf_download','annually','none','since 1974','["endowment_size_usd","asset_allocation","private_equity_pct","top_managers","commitments_disclosed"]',1,70),
 ('src_endow_yale','global','Yale','endowment_holdings','Yale Endowment Annual Report','https://investments.yale.edu/reports','pdf_download','annually','none','since 1985','["endowment_size_usd","asset_allocation","venture_capital_pct","private_equity_pct","real_assets_pct","absolute_return_pct"]',1,70),
 ('src_endow_stanford','global','Stanford','endowment_holdings','Stanford Management Company Annual Report','https://smc.stanford.edu/annual-report/','pdf_download','annually','none','since 1991','["endowment_size_usd","asset_allocation","private_equity_pct","real_estate_pct"]',1,70),
 ('src_endow_princeton','global','Princeton','endowment_holdings','PRINCO Annual Report','https://princo.princeton.edu','pdf_download','annually','none','since 1987','["endowment_size_usd","asset_allocation","private_equity_pct"]',1,70),
 ('src_endow_mit','global','MIT','endowment_holdings','MITIMCo Annual Report','https://mitimco.org/annual-report/','pdf_download','annually','none','since 2004','["endowment_size_usd","asset_allocation","private_equity_pct","real_estate_pct"]',1,70),
 ('src_endow_cambridge','global','University of Cambridge','endowment_holdings','Cambridge Endowment Fund Annual Report','https://www.investmentoffice.cam.ac.uk','pdf_download','annually','none','since 2007','["endowment_size_gbp","asset_allocation","private_equity_pct"]',1,70),
 ('src_endow_oxford','global','University of Oxford','endowment_holdings','Oxford University Endowment Management Annual Report','https://www.ouem.co.uk','pdf_download','annually','none','since 2008','["endowment_size_gbp","asset_allocation","private_equity_pct"]',1,70),
 ('src_endow_columbia','global','Columbia','endowment_holdings','Columbia Investment Management Co.','https://www.cimc.columbia.edu','pdf_download','annually','none','since 2002','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_penn','global','U Penn','endowment_holdings','Penn Office of Investments Annual Report','https://www.upenn.edu/investments/','pdf_download','annually','none','since 1999','["endowment_size_usd","asset_allocation","private_equity_pct"]',1,70),
 ('src_endow_utimco','global','UTIMCO','endowment_holdings','U of Texas / Texas A&M (UTIMCO) Annual Report','https://www.utimco.org','pdf_download','annually','none','since 1996','["aum_usd","asset_allocation","private_equity_pct","ranking"]',1,70),
 ('src_endow_notredame','global','Notre Dame','endowment_holdings','Notre Dame Investment Office Annual Report','https://investment.nd.edu','pdf_download','annually','none','since 1995','["endowment_size_usd","asset_allocation","private_equity_pct"]',1,70),
 ('src_endow_northwestern','global','Northwestern','endowment_holdings','Northwestern University Endowment Report','https://www.northwestern.edu/investment/','pdf_download','annually','none','since 2005','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_duke','global','Duke','endowment_holdings','DUMAC Annual Report','https://dumac.duke.edu','pdf_download','annually','none','since 1990','["endowment_size_usd","asset_allocation","private_equity_pct"]',1,70),
 ('src_endow_umich','global','U Michigan','endowment_holdings','U of Michigan Office of Investments Report','https://investments.umich.edu','pdf_download','annually','none','since 2000','["endowment_size_usd","asset_allocation","venture_capital_pct"]',1,70),
 ('src_endow_cornell','global','Cornell','endowment_holdings','Cornell Investment Office Annual Report','https://www.dfa.cornell.edu/treasurer/investment-office','pdf_download','annually','none','since 2000','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_dartmouth','global','Dartmouth','endowment_holdings','Dartmouth Investment Office Annual Report','https://www.dartmouth.edu/investments/','pdf_download','annually','none','since 2001','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_brown','global','Brown','endowment_holdings','Brown Investment Office Annual Report','https://www.brown.edu/about/administration/treasurer/investments','pdf_download','annually','none','since 2004','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_uchicago','global','U Chicago','endowment_holdings','U of Chicago Office of Investments Report','https://investments.uchicago.edu','pdf_download','annually','none','since 2000','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_jhu','global','Johns Hopkins','endowment_holdings','JHU Endowment Annual Report','https://investments.jhu.edu','pdf_download','annually','none','since 2010','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_uva','global','UVIMCO','endowment_holdings','UVIMCO Annual Report','https://www.uvimco.org','pdf_download','annually','none','since 2004','["endowment_size_usd","asset_allocation","private_equity_pct"]',1,70),
 ('src_endow_unc','global','UNC Management Co.','endowment_holdings','UNC Investment Fund Annual Report','https://unc-imc.com','pdf_download','annually','none','since 2003','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_vanderbilt','global','Vanderbilt','endowment_holdings','Vanderbilt University Endowment Report','https://finance.vanderbilt.edu/treasury/investments.php','pdf_download','annually','none','since 2008','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_emory','global','Emory','endowment_holdings','Emory Investment Management Annual Report','https://eim.emory.edu','pdf_download','annually','none','since 2008','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_rice','global','Rice','endowment_holdings','Rice Management Company Annual Report','https://rmc.rice.edu','pdf_download','annually','none','since 2005','["endowment_size_usd","asset_allocation","private_equity_pct"]',1,70),
 ('src_endow_uw','global','U Washington','endowment_holdings','UW Investment Management Co. (UWINCO)','https://www.washington.edu/treasury/uwinco/','pdf_download','annually','none','since 2007','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_nyu','global','NYU','endowment_holdings','NYU Office of Investments Report','https://www.nyu.edu/about/leadership-university-administration/office-of-the-president/office-of-the-vice-president-for-finance.html','pdf_download','annually','none','since 2010','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_usc','global','USC','endowment_holdings','USC Investment Office Report','https://about.usc.edu/wp-content/uploads/','pdf_download','annually','none','since 2010','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_cmu','global','Carnegie Mellon','endowment_holdings','CMU Office of Investments Report','https://www.cmu.edu/finance/treasurer/investments/','pdf_download','annually','none','since 2008','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_caltech','global','Caltech','endowment_holdings','Caltech Endowment Annual Report','https://finance.caltech.edu/about/investments','pdf_download','annually','none','since 2008','["endowment_size_usd","asset_allocation"]',1,70),
 ('src_endow_wisc','global','U Wisconsin Foundation','endowment_holdings','U Wisconsin Foundation Annual Report','https://www.supportuw.org','pdf_download','annually','none','since 2005','["endowment_size_usd","asset_allocation"]',1,70);

-- Tier A — Sovereign Wealth Funds
INSERT OR REPLACE INTO vc_sources (id, jurisdiction, authority, data_type, source_name, base_url, access_pattern, refresh_cadence, authentication, historical_depth, data_fields_json, enabled, priority) VALUES
 ('src_swf_temasek','sg','Temasek','sovereign_wealth_holdings','Temasek Review Annual Report','https://www.temasek.com.sg/en/our-financials/library/temasek-review','pdf_download','annually','none','since 1974','["nav_sgd","portfolio_composition","major_investments","new_investments","divestments","sector_allocation","geo_allocation"]',1,70),
 ('src_swf_gic','sg','GIC','sovereign_wealth_holdings','GIC Annual Report','https://www.gic.com.sg/reports/','pdf_download','annually','none','since 1981','["aum_estimate_usd","asset_allocation","private_equity_pct","real_estate_pct","geographic_allocation"]',1,70),
 ('src_swf_nbim','eu-no','NBIM','sovereign_wealth_holdings','Norges Bank Investment Management Holdings','https://www.nbim.no/en/the-fund/holdings/','json_api','annually','none','since 1998','["aum_nok","equity_holdings","bond_holdings","real_estate_holdings","renewable_infra"]',1,70),
 ('src_swf_mubadala','global','Mubadala','sovereign_wealth_holdings','Mubadala Annual Report','https://www.mubadala.com/en/our-investments','pdf_download','annually','none','since 2007','["aum_usd","portfolio","sector_allocation","direct_investments"]',1,70),
 ('src_swf_adia','global','ADIA','sovereign_wealth_holdings','ADIA Review','https://www.adia.ae/en/Review-Library','pdf_download','annually','none','since 2009','["aum_estimate_usd","asset_class_breakdown","geographic_allocation"]',1,70),
 ('src_swf_pif','global','PIF','sovereign_wealth_holdings','Saudi Public Investment Fund Annual Report','https://www.pif.gov.sa/en/disclosures','pdf_download','annually','none','since 2018','["aum_usd","portfolio_companies","sector_allocation","giga_projects"]',1,70),
 ('src_swf_cic','cn','CIC','sovereign_wealth_holdings','China Investment Corporation Annual Report','http://www.china-inv.cn/chinainvcorpEN/Investments/Annual_Report.shtml','pdf_download','annually','none','since 2007','["aum_usd","public_equity_pct","alternatives_pct","fixed_income_pct"]',1,70),
 ('src_swf_kia','global','KIA','sovereign_wealth_holdings','Kuwait Investment Authority Annual Review','https://www.kia.gov.kw','pdf_download','annually','none','since 1953','["aum_estimate_usd","portfolio","public_equity","alternatives"]',1,70),
 ('src_swf_nzsf','global','NZ Super Fund','sovereign_wealth_holdings','New Zealand Superannuation Fund Annual Report','https://www.nzsuperfund.nz/publications','pdf_download','annually','none','since 2003','["aum_nzd","asset_allocation","private_equity_pct","infrastructure_pct"]',1,70),
 ('src_swf_future','au','Future Fund','sovereign_wealth_holdings','Australian Future Fund Portfolio Update','https://www.futurefund.gov.au/investment/investment-portfolio-updates','pdf_download','quarterly','none','since 2006','["aum_aud","asset_allocation","private_equity_pct","alternatives_pct"]',1,70),
 ('src_swf_qia','global','QIA','sovereign_wealth_holdings','Qatar Investment Authority Disclosures','https://www.qia.qa','html_scrape','annually','none','since 2005','["aum_estimate_usd","sector_focus","known_investments"]',1,70),
 ('src_swf_oif','global','Oman Investment Authority','sovereign_wealth_holdings','Oman Investment Authority Annual Report','https://www.oia.gov.om','pdf_download','annually','none','since 2020','["aum_usd","sector_allocation"]',1,70),
 ('src_swf_khazanah','global','Khazanah Nasional','sovereign_wealth_holdings','Khazanah Nasional Annual Review','https://www.khazanah.com.my/our-publications/','pdf_download','annually','none','since 1993','["aum_myr","portfolio","sector_allocation"]',1,70);

-- ============================================================
-- Tier B — Press release wires + tech / regional press
-- ============================================================
INSERT OR REPLACE INTO vc_sources (id, jurisdiction, authority, data_type, source_name, base_url, access_pattern, refresh_cadence, authentication, historical_depth, data_fields_json, enabled, priority) VALUES
 ('src_wire_prnewswire','global','PR Newswire','press_release','PR Newswire News Releases','https://www.prnewswire.com/news-releases/financial-services-latest-news/venture-capital-list/','rss_feed','realtime','none','since 1954','["headline","body","dateline","ticker","company","contact","categories"]',1,40),
 ('src_wire_businesswire','global','BusinessWire','press_release','BusinessWire News','https://www.businesswire.com/portal/site/home/news/','rss_feed','realtime','none','since 1961','["headline","body","dateline","company","ticker","categories"]',1,40),
 ('src_wire_globenewswire','global','GlobeNewswire','press_release','GlobeNewswire News Feed','https://www.globenewswire.com/rss/','rss_feed','realtime','none','since 1998','["headline","body","dateline","company","ticker"]',1,40),
 ('src_wire_cision','global','Cision','press_release','Cision PR Newswire Distribution','https://www.cision.com/news/','rss_feed','realtime','none','since 1867','["headline","body","company","contact"]',1,40),
 ('src_wire_accesswire','global','AccessWire','press_release','AccessWire News Distribution','https://www.accesswire.com/newsroom/','rss_feed','realtime','none','since 2009','["headline","body","company","ticker"]',1,40),
 ('src_press_techcrunch','global','TechCrunch','tech_press','TechCrunch Venture Coverage','https://techcrunch.com/category/venture/','rss_feed','hourly','none','since 2005','["headline","body","author","date","companies_mentioned","investors_mentioned","round_size","stage"]',1,40),
 ('src_press_theinfo','global','The Information','tech_press','The Information','https://www.theinformation.com','html_scrape','daily','login','since 2013','["headline","body","companies_mentioned","investors_mentioned"]',0,40),
 ('src_press_axios_pr','global','Axios','tech_press','Axios Pro Rata Newsletter','https://www.axios.com/newsletters/axios-pro-rata','rss_feed','daily','none','since 2018','["headline","items","deal_announcements","exits"]',1,40),
 ('src_press_term_sheet','global','Fortune','tech_press','Fortune Term Sheet','https://fortune.com/tag/term-sheet/','rss_feed','daily','none','since 2014','["headline","deals","exits","people_moves"]',1,40),
 ('src_press_strictly_vc','global','Strictly VC','tech_press','Strictly VC Daily Newsletter','https://www.strictlyvc.com','html_scrape','daily','none','since 2013','["headline","items","funding_announcements"]',1,40),
 ('src_press_cb_news','global','Crunchbase News','tech_press','Crunchbase News','https://news.crunchbase.com','rss_feed','hourly','none','since 2017','["headline","body","companies","investors","round_size","stage"]',1,40),
 ('src_press_cmn','cn','China Money Network','regional_press','China Money Network','https://www.chinamoneynetwork.com','rss_feed','daily','none','since 2011','["headline","companies","investors","round_size"]',1,40),
 ('src_press_techinasia','global','Tech in Asia','regional_press','Tech in Asia','https://www.techinasia.com','rss_feed','daily','none','since 2010','["headline","companies","investors","round_size","country"]',1,40),
 ('src_press_sifted','eu','Sifted','regional_press','Sifted (European Tech)','https://sifted.eu','rss_feed','daily','none','since 2019','["headline","companies","investors","round_size","country"]',1,40),
 ('src_press_eustartups','eu','EU-Startups','regional_press','EU-Startups','https://www.eu-startups.com','rss_feed','daily','none','since 2010','["headline","companies","investors","round_size","country"]',1,40),
 ('src_press_pitchbook_news','global','PitchBook News','tech_press','PitchBook News (free articles)','https://pitchbook.com/news','rss_feed','daily','none','since 2007','["headline","body","companies","investors"]',1,40);

-- ============================================================
-- Tier C — Accelerator cohorts + conferences + podcasts
-- ============================================================
INSERT OR REPLACE INTO vc_sources (id, jurisdiction, authority, data_type, source_name, base_url, access_pattern, refresh_cadence, authentication, historical_depth, data_fields_json, enabled, priority) VALUES
 ('src_acc_yc','global','Y Combinator','accelerator_cohort','Y Combinator Companies Directory','https://www.ycombinator.com/companies','html_scrape','weekly','none','since 2005','["company_name","batch","founded","status","industry","founders","website","one_liner"]',1,20),
 ('src_acc_techstars','global','Techstars','accelerator_cohort','Techstars Portfolio Directory','https://www.techstars.com/portfolio','html_scrape','weekly','none','since 2006','["company_name","program","year","status","industry","founders","website"]',1,20),
 ('src_acc_500','global','500 Global','accelerator_cohort','500 Global Portfolio','https://500.co/companies','html_scrape','weekly','none','since 2010','["company_name","batch","status","industry","founders","website"]',1,20),
 ('src_acc_angelpad','global','AngelPad','accelerator_cohort','AngelPad Cohort Pages','https://angelpad.com','html_scrape','quarterly','none','since 2010','["company_name","class","status","industry","website"]',1,20),
 ('src_acc_pnp','global','Plug and Play','accelerator_cohort','Plug and Play Tech Center Portfolio','https://www.plugandplaytechcenter.com/portfolio/','html_scrape','monthly','none','since 2006','["company_name","program","industry","status"]',1,20),
 ('src_acc_masschallenge','global','MassChallenge','accelerator_cohort','MassChallenge Portfolio','https://masschallenge.org/startups','html_scrape','quarterly','none','since 2010','["company_name","cohort","industry","status","website"]',1,20),
 ('src_acc_seedcamp','eu','Seedcamp','accelerator_cohort','Seedcamp Portfolio','https://seedcamp.com/portfolio','html_scrape','monthly','none','since 2007','["company_name","cohort","industry","website"]',1,20),
 ('src_acc_entrepreneurs_first','eu','Entrepreneur First','accelerator_cohort','Entrepreneur First Portfolio','https://www.joinef.com/portfolio','html_scrape','monthly','none','since 2011','["company_name","cohort","city","industry","website"]',1,20),
 ('src_conf_websummit','global','Web Summit','conference_directory','Web Summit Startups Directory','https://websummit.com/startups','html_scrape','annually','none','since 2009','["startup_name","attending_year","industry","stage","country"]',1,20),
 ('src_conf_sxsw','global','SXSW','conference_directory','SXSW Pitch Finalists','https://www.sxsw.com/conference/sxsw-pitch/','html_scrape','annually','none','since 2009','["startup_name","year","category","status"]',1,20),
 ('src_conf_disrupt','global','TechCrunch','conference_directory','TechCrunch Disrupt Battlefield','https://techcrunch.com/events/tc-disrupt-2026/','html_scrape','annually','none','since 2007','["startup_name","year","category","status"]',1,20),
 ('src_conf_slush','eu-fi','Slush','conference_directory','Slush Startups List','https://www.slush.org','html_scrape','annually','none','since 2008','["startup_name","year","industry","stage","country"]',1,20),
 ('src_pod_20vc','global','Listen Notes','podcast_directory','20VC Podcast Index','https://www.listennotes.com/podcasts/the-twenty-minute-vc-harry-stebbings-Bp_Wn35z0xR/','rss_feed','weekly','none','since 2015','["episode_title","guest_name","guest_firm","topics","transcript_link"]',1,20),
 ('src_pod_invest_like_best','global','Listen Notes','podcast_directory','Invest Like the Best Podcast Index','https://www.listennotes.com/podcasts/invest-like-the-best-with-patrick-OvyzfkPwYNX/','rss_feed','weekly','none','since 2017','["episode_title","guest_name","guest_firm","topics"]',1,20),
 ('src_pod_acquired','global','Listen Notes','podcast_directory','Acquired Podcast Index','https://www.listennotes.com/podcasts/acquired-ben-gilbert-and-david-rosenthal-bsdAasTdQp_/','rss_feed','weekly','none','since 2016','["episode_title","companies_covered","investors_mentioned","transcript_link"]',1,20),
 ('src_curated_signalnfx','us-federal','Signal','startup_database','Signal NFX Founder/Investor Database','https://signal.nfx.com','html_scrape','weekly','none','since 2018','["person_name","role","firm","focus","company_history","location"]',1,40);
