// Country name → ISO-3166-1 alpha-2 lookup. Lowercase, no diacritics, no
// "the". Includes common alternates ("uk", "usa", "south korea", etc.).
// Generated/curated for the 50 countries most common in VC datasets, plus
// every EU/G20 member. Extend as new aliases appear in upload audits.

export const COUNTRY_NAME_TO_ISO2: Record<string, string> = {
  "united states": "US", "united states of america": "US", "usa": "US", "u s a": "US", "us": "US", "america": "US",
  "united kingdom": "GB", "uk": "GB", "great britain": "GB", "britain": "GB", "england": "GB", "scotland": "GB", "wales": "GB", "northern ireland": "GB",
  "canada": "CA",
  "mexico": "MX",
  "brazil": "BR", "brasil": "BR",
  "argentina": "AR",
  "chile": "CL",
  "colombia": "CO",
  "peru": "PE",
  "france": "FR",
  "germany": "DE", "deutschland": "DE",
  "spain": "ES", "espana": "ES",
  "portugal": "PT",
  "italy": "IT", "italia": "IT",
  "netherlands": "NL", "holland": "NL",
  "belgium": "BE",
  "luxembourg": "LU",
  "switzerland": "CH",
  "austria": "AT",
  "ireland": "IE", "republic of ireland": "IE",
  "denmark": "DK",
  "sweden": "SE",
  "norway": "NO",
  "finland": "FI",
  "iceland": "IS",
  "poland": "PL",
  "czech republic": "CZ", "czechia": "CZ",
  "slovakia": "SK",
  "hungary": "HU",
  "romania": "RO",
  "bulgaria": "BG",
  "greece": "GR",
  "croatia": "HR",
  "slovenia": "SI",
  "estonia": "EE",
  "latvia": "LV",
  "lithuania": "LT",
  "ukraine": "UA",
  "russia": "RU", "russian federation": "RU",
  "turkey": "TR", "turkiye": "TR",
  "israel": "IL",
  "united arab emirates": "AE", "uae": "AE", "emirates": "AE",
  "saudi arabia": "SA", "ksa": "SA",
  "qatar": "QA",
  "bahrain": "BH",
  "kuwait": "KW",
  "oman": "OM",
  "egypt": "EG",
  "south africa": "ZA",
  "nigeria": "NG",
  "kenya": "KE",
  "ghana": "GH",
  "morocco": "MA",
  "india": "IN", "bharat": "IN",
  "china": "CN", "people s republic of china": "CN", "prc": "CN", "mainland china": "CN",
  "hong kong": "HK", "hk": "HK",
  "taiwan": "TW", "republic of china": "TW",
  "japan": "JP", "nippon": "JP",
  "south korea": "KR", "korea": "KR", "republic of korea": "KR",
  "north korea": "KP", "dprk": "KP",
  "singapore": "SG", "sg": "SG",
  "malaysia": "MY",
  "indonesia": "ID",
  "philippines": "PH",
  "thailand": "TH",
  "vietnam": "VN", "viet nam": "VN",
  "cambodia": "KH",
  "laos": "LA",
  "myanmar": "MM", "burma": "MM",
  "bangladesh": "BD",
  "pakistan": "PK",
  "sri lanka": "LK",
  "nepal": "NP",
  "australia": "AU", "au": "AU",
  "new zealand": "NZ", "nz": "NZ",
  "fiji": "FJ",
  // Common "EU" / regions appear as countries in some sheets — map to null
  // by NOT listing them so callers can still attach them as geo_focus tags.
};
